import { DEFAULT_ENDPOINT } from "./settings/settings";

export default {
  ONBOARDING_COMPANY_ADMINISTRATORS_ME: `${DEFAULT_ENDPOINT}o/company/administrators/me/`,
  ONBOARDING_COMPANY_ADMINISTRATORS: `${DEFAULT_ENDPOINT}o/company/administrators/`,
  ONBOARDING_COMPANY_DEBTS: `${DEFAULT_ENDPOINT}o/company/debts/`,
  ONBOARDING_COMPANY_PROXIES: `${DEFAULT_ENDPOINT}o/company/proxies/`,
  ONBOARDING_COMPANY: `${DEFAULT_ENDPOINT}o/company/`,
  ONBOARDING_FINISH: `${DEFAULT_ENDPOINT}o/finish/`,

  ONBOARDING_QUIZ: `${DEFAULT_ENDPOINT}o/quiz/`,
  ONBOARDING_DOCUMENTS: `${DEFAULT_ENDPOINT}o/documents/`,
  ONBOARDING_SUMMARY: `${DEFAULT_ENDPOINT}o/summary/`,
  ONBOARDING_TERMS: `${DEFAULT_ENDPOINT}o/terms/`,

  ONBOARDING_USERS_ME: `${DEFAULT_ENDPOINT}o/users/me/`,
  ONBOARDING_USERS: `${DEFAULT_ENDPOINT}o/users/`,

  PUBLIC_BANKS: `${DEFAULT_ENDPOINT}p/banks/`,
  PUBLIC_LOGIN: `${DEFAULT_ENDPOINT}p/login/`,
  PUBLIC_PASSWORD_RECOVER: `${DEFAULT_ENDPOINT}p/password/recover/`,
  PUBLIC_USER_BASIC_INFO: `${DEFAULT_ENDPOINT}p/user/basic-info/`,

  USER_COMPANIES: `${DEFAULT_ENDPOINT}u/companies/`,

  REGISTER_PASSWORD: `${DEFAULT_ENDPOINT}o/users/me/password/`
};
